apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-api
  template:
    metadata:
      labels:
        app: devops-api
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: devops-api
        image: acrdevopslab01.azurecr.io/devops-api:v1
        ports:
        - containerPort: 5000